apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-policies
  namespace: argocd
spec:
  project: pulpit-v2
  source:
    repoURL: https://github.com/manynames3/pulpit-v2.git
    targetRevision: main
    path: manifests/tenants
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
