apiVersion: v1
kind: Namespace
metadata:
  name: bethel-atlanta
  labels:
    app.kubernetes.io/part-of: pulpit-v2
    pulpit.ai/tenant: bethel-atlanta
    pulpit.ai/display-name: atlanta-bethel-church
  annotations:
    pulpit.ai/display-name: Atlanta Bethel Church
