{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "pulpit.fullname" . }}-app-secrets
  labels:
    {{- include "pulpit.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
  target:
    name: {{ include "pulpit.fullname" . }}-app-secrets
    creationPolicy: {{ .Values.externalSecrets.target.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecrets.target.deletionPolicy }}
  {{- with .Values.externalSecrets.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.externalSecrets.dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
