{{- if .Values.global.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pulpit.serviceAccountName" . }}
  labels:
    {{- include "pulpit.labels" . | nindent 4 }}
  {{- if or .Values.global.irsa.enabled .Values.global.serviceAccount.annotations }}
  annotations:
    {{- if .Values.global.irsa.enabled }}
    eks.amazonaws.com/role-arn: {{ .Values.global.irsa.roleArn | quote }}
    {{- end }}
    {{- with .Values.global.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
